import 'package:felicitime/features/capsules/model/capsule.dart';

class AppCapsules {

  /// Tags associated with the capsule
  /// e.g. 'free', 'premium', 'all_price', 'all_seasons', 'spring', 'summer', 'autumn', 'winter', 'all_family', etc.
  ///
  /// Family tags: 'family_all', 'family_yes', 'family_near', 'family_no'
  /// Price tags: 'price_all', 'price_free', 'price_little', 'price_high'
  /// Season tags: 'season_all', 'season_spring', 'season_summer', 'season_autumn', 'season_winter'
  ///
  static List<Capsule> capsules = [
    Capsule(
      id: 1,
      title: "Ecrire un petit poême",
      description: "Laissez libre cours à votre créativité en écrivant un poème sur un sujet qui vous inspire. Exprimez vos émotions et vos pensées à travers les mots.",
      duration: Duration(minutes: 30),
      tags: ['price_all', 'season_all', 'family_all', 'creativity'],
    ),
    Capsule(
      id: 2,
      title: "Prendre en photo un papillon",
      description: "Sortez prendre l'air et capturez la beauté d'un papillon en photo. Prenez un moment pour apprécier la nature qui vous entoure.",
      duration: Duration(minutes: 60),
      tags: ['price_all', 'season_spring', 'season_summer', 'season_outdoor', 'family_all', 'focus'],
    ),
    Capsule(
      id: 3,
      title: "Cuisiner un gateau",
      description: "Préparez un délicieux gâteau en suivant une recette ou laissez-vous guider par votre inspiration. Profitez du processus de cuisson et savourez le résultat final.",
      duration: Duration(minutes: 60),
      tags: ['price_all', 'season_all', 'family_all', 'creativity', 'miam'],
    ),
    Capsule(
      id: 4,
      title: "Prendre un café au soleil",
      description: "Profitez d'une pause détente en savourant un café en plein air, sous le soleil. Fermez les yeux et laissez-vous imprégner par la chaleur et la lumière naturelle.",
      duration: Duration(minutes: 5),
      tags: ['price_all', 'season_all', 'family_all', 'meditation'],
    ),
    Capsule(
      id: 4,
      title: "Prendre un thé au soleil",
      description: "Profitez d'une pause détente en savourant un thé en plein air, sous le soleil. Fermez les yeux et laissez-vous imprégner par la chaleur et la lumière naturelle.",
      duration: Duration(minutes: 5),
      tags: ['price_all', 'season_all', 'family_all', 'meditation'],
    ),
    Capsule(
      id: 5,
      title: "Ceuillir un petit bouquet de fleurs",
      description: "",
      duration: Duration(minutes: 5),
      tags: ['price_all', 'season_spring', 'season_summer', 'season_autumn', 'family_all'],
    ),
    Capsule(
      id: 6,
      title: "Faire une séance de cinéma",
      description: "",
      duration: Duration(minutes: 120),
      tags: ['price_little', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 7,
      title: "S'allonger dans l'herbe et regarder les nuages",
      description: "",
      duration: Duration(minutes: 10),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 8,
      title: "Regarder un dessin animé ou un film d'enfance",
      description: "",
      duration: Duration(minutes: 60),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 9,
      title: "Se promener dans la nature (le long de l'eau ou sous les arbres)",
      description: "",
      duration: Duration(minutes: 60),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 10,
      title: "Faire un compliment à quelqu'un que l'on aime ou que l'on apprécie",
      description: "",
      duration: Duration(minutes: 1),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 11,
      title: "Faire un coloriage",
      description: "",
      duration: Duration(minutes: 15),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 12,
      title: "S'offrir un massage",
      description: "",
      duration: Duration(minutes: 60),
      tags: ['price_high', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 13,
      title: "Aller chez le coiffeur",
      description: "",
      duration: Duration(minutes: 60),
      tags: ['price_high', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 14,
      title: "Ranger une pièce de sa maison",
      description: "",
      duration: Duration(minutes: 60),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 15,
      title: "Faire dons de 3 choses qui nous encombre",
      description: "",
      duration: Duration(minutes: 30),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 16,
      title: "Ouvrir sa boite a souvenir",
      description: "",
      duration: Duration(minutes: 30),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 17,
      title: "Regarder un album photo",
      description: "",
      duration: Duration(minutes: 15),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 18,
      title: "Faire une playlist des musiques de son adolescence",
      description: "",
      duration: Duration(minutes: 30),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 19,
      title: "Appeler quelqu'un",
      description: "",
      duration: Duration(minutes: 15),
      tags: ['price_all', 'season_all', 'family_yes', 'family_near'],
    ),
    Capsule(
      id: 20,
      title: "Faire une origami",
      description: "",
      duration: Duration(minutes: 10),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 21,
      title: "Chercher un trèfle a 4 feuilles",
      description: "",
      duration: Duration(minutes: 30),
      tags: ['price_all', 'season_spring', 'season_summer', 'family_all'],
    ),
    Capsule(
      id: 22,
      title: "Emprunter un livre à la bibliothèque",
      description: "",
      duration: Duration(minutes: 60),
      tags: ['price_little', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 23,
      title: "Imprimer un petit album photo",
      description: "",
      duration: Duration(minutes: 60),
      tags: ['price_little', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 24,
      title: "Faire du tri dans ses vêtements",
      description: "",
      duration: Duration(minutes: 60),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 25,
      title: "Commencer un herbier",
      description: "",
      duration: Duration(minutes: 60),
      tags: ['price_all', 'season_spring', 'season_summer', 'family_all'],
    ),
    Capsule(
      id: 26,
      title: "Faire un petit montage photo",
      description: "",
      duration: Duration(minutes: 60),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 27,
      title: "Aller au marché",
      description: "",
      duration: Duration(minutes: 60),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 28,
      title: "Regarder les étoiles",
      description: "",
      duration: Duration(minutes: 10),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 29,
      title: "Regarder ses vieilles photos",
      description: "",
      duration: Duration(minutes: 10),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 30,
      title: "Fabriquer une boite à souvenirs",
      description: "",
      duration: Duration(minutes: 60),
      tags: ['price_little', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 31,
      title: "Aller au zoo",
      description: "",
      duration: Duration(minutes: 120),
      tags: ['price_high', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 32,
      title: "Aller visiter un musée",
      description: "",
      duration: Duration(minutes: 120),
      tags: ['price_high', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 33,
      title: "Aller visiter un aquarium",
      description: "",
      duration: Duration(minutes: 120),
      tags: ['price_high', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 34,
      title: "Essayer une nouvelle activité physique",
      description: "",
      duration: Duration(minutes: 60),
      tags: ['price_little', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 35,
      title: "Commencer son propre livre de recettes",
      description: "",
      duration: Duration(minutes: 15),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 36,
      title: "Cuisiner un plat étranger",
      description: "",
      duration: Duration(minutes: 60),
      tags: ['price_little', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 37,
      title: "Aller au restaurants",
      description: "",
      duration: Duration(minutes: 60),
      tags: ['price_high', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 38,
      title: "Organiser un gouter pour ses proches",
      description: "",
      duration: Duration(minutes: 120),
      tags: ['price_little', 'season_all', 'family_all'],
    ),
  ];

}