import 'package:felicitime/features/capsules/model/capsule.dart';

class AppCapsules {

  /// Tags associated with the capsule
  /// e.g. 'free', 'premium', 'all_price', 'all_seasons', 'spring', 'summer', 'autumn', 'winter', 'all_family', etc.
  ///
  /// Family tags: 'family_all', 'family_yes', 'family_near', 'family_no'
  /// Price tags: 'price_all', 'price_free', 'price_little', 'price_high'
  /// Season tags: 'season_all', 'season_spring', 'season_summer', 'season_autumn', 'season_winter'
  ///
  static List<Capsule> capsules = [
    Capsule(
      id: 1,
      title: "Ecrire un petit poême",
      description: "Laissez libre cours à votre créativité en écrivant un poème sur un sujet qui vous inspire. Exprimez vos émotions et vos pensées à travers les mots.",
      duration: Duration(minutes: 30),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 2,
      title: "Prendre en photo un papillon",
      description: "Sortez prendre l'air et capturez la beauté d'un papillon en photo. Prenez un moment pour apprécier la nature qui vous entoure.",
      duration: Duration(minutes: 60),
      tags: ['price_all', 'season_spring', 'season_summer', 'season_outdoor', 'family_all'],
    ),
    Capsule(
      id: 3,
      title: "Cuisiner un gateau",
      description: "Préparez un délicieux gâteau en suivant une recette ou laissez-vous guider par votre inspiration. Profitez du processus de cuisson et savourez le résultat final.",
      duration: Duration(minutes: 60),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 4,
      title: "Prendre un café au soleil",
      description: "Profitez d'une pause détente en savourant un café en plein air, sous le soleil. Fermez les yeux et laissez-vous imprégner par la chaleur et la lumière naturelle.",
      duration: Duration(minutes: 5),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 4,
      title: "Prendre un thé au soleil",
      description: "Profitez d'une pause détente en savourant un thé en plein air, sous le soleil. Fermez les yeux et laissez-vous imprégner par la chaleur et la lumière naturelle.",
      duration: Duration(minutes: 5),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 5,
      title: "Ceuillir un petit bouquet de fleurs",
      description: "Sortez dans votre jardin ou dans un parc et cueillez un petit bouquet de fleurs sauvages. Prenez le temps d'apprécier la beauté de la nature et de créer un arrangement floral simple mais charmant.",
      duration: Duration(minutes: 5),
      tags: ['price_all', 'season_spring', 'season_summer', 'season_autumn', 'family_all'],
    ),
    Capsule(
      id: 6,
      title: "Faire une séance de cinéma",
      description: "Organisez une séance de cinéma à la maison en choisissant un film que vous aimez ou que vous avez envie de découvrir. Préparez du popcorn, installez-vous confortablement et profitez d'un moment de détente devant l'écran.",
      duration: Duration(minutes: 120),
      tags: ['price_little', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 7,
      title: "S'allonger dans l'herbe et regarder les nuages",
      description: "Allongez-vous dans un endroit calme, comme un parc ou votre jardin, et laissez votre esprit vagabonder en regardant les nuages passer. Essayez de trouver des formes ou des images dans les nuages pour stimuler votre imagination.",
      duration: Duration(minutes: 10),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 8,
      title: "Regarder un dessin animé ou un film d'enfance",
      description: "Plongez-vous dans la nostalgie en regardant un dessin animé ou un film que vous aimiez lorsque vous étiez enfant.",
      duration: Duration(minutes: 60),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 9,
      title: "Se promener dans la nature (le long de l'eau ou sous les arbres)",
      description: "Faites une promenade paisible dans la nature, que ce soit le long d'une rivière, d'un lac ou sous les arbres d'une forêt. Prenez le temps de respirer l'air frais, d'écouter les sons de la nature et de vous reconnecter avec votre environnement.",
      duration: Duration(minutes: 60),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 10,
      title: "Faire un compliment à quelqu'un que l'on aime ou que l'on apprécie",
      description: "Prenez un moment pour exprimer votre gratitude et votre affection envers quelqu'un que vous aimez ou que vous appréciez. Faites-lui un compliment sincère pour lui montrer à quel point il compte pour vous.",
      duration: Duration(minutes: 1),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 11,
      title: "Faire un coloriage",
      description: "Prenez un livre de coloriage ou imprimez des dessins à colorier, et laissez libre cours à votre créativité en coloriant. Choisissez des couleurs qui vous inspirent et profitez du processus de création pour vous détendre et vous amuser.",
      duration: Duration(minutes: 15),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 12,
      title: "S'offrir un massage",
      description: "Prenez soin de vous en vous offrant un massage relaxant.",
      duration: Duration(minutes: 60),
      tags: ['price_high', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 13,
      title: "Aller chez le coiffeur",
      description: "Changez de look ou rafraîchissez votre coupe en allant chez le coiffeur. Prenez le temps de vous faire chouchouter et de vous sentir bien dans votre peau.",
      duration: Duration(minutes: 60),
      tags: ['price_high', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 14,
      title: "Ranger une pièce de sa maison",
      description: "Choisissez une pièce de votre maison qui a besoin d'un peu d'organisation et prenez le temps de la ranger. Triez les objets, jetez ce dont vous n'avez plus besoin et réorganisez l'espace.",
      duration: Duration(minutes: 60),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 15,
      title: "Faire dons de 3 choses qui nous encombre",
      description: "Faites du tri dans vos affaires et choisissez trois objets que vous n'utilisez plus ou qui ne vous apportent plus de joie. Donnez-les à une association caritative, à un ami ou à un membre de votre famille qui pourrait en avoir besoin.",
      duration: Duration(minutes: 30),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 16,
      title: "Ouvrir sa boite a souvenir",
      description: "Si vous avez une boite à souvenirs, prenez le temps de l'ouvrir et de redécouvrir les objets et les souvenirs qu'elle contient. Revivez les moments heureux associés à ces souvenirs et laissez-vous emporter par la nostalgie.",
      duration: Duration(minutes: 30),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 17,
      title: "Regarder un album photo",
      description: "Prenez un album photo, que ce soit un album physique ou numérique, et parcourez les photos qu'il contient. Revivez les moments heureux associés à ces photos et laissez-vous emporter par la nostalgie.",
      duration: Duration(minutes: 15),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 18,
      title: "Faire une playlist des musiques de son adolescence",
      description: "Créez une playlist de vos chansons préférées de votre adolescence. Plongez-vous dans les souvenirs associés à ces chansons et laissez la musique vous transporter dans le temps.",
      duration: Duration(minutes: 30),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 19,
      title: "Appeler quelqu'un",
      description: "Prenez le temps d'appeler quelqu'un que vous aimez ou que vous appréciez. Partagez un moment de conversation, échangez des nouvelles et renforcez votre lien avec cette personne.",
      duration: Duration(minutes: 15),
      tags: ['price_all', 'season_all', 'family_yes', 'family_near'],
    ),
    Capsule(
      id: 20,
      title: "Faire une origami",
      description: "Apprenez à faire une origami en suivant un tutoriel en ligne ou en utilisant un livre d'origami. Choisissez un modèle qui vous plaît et laissez-vous guider par les étapes pour créer une belle figure en papier.",
      duration: Duration(minutes: 10),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 21,
      title: "Chercher un trèfle a 4 feuilles",
      description: "Sortez dans un parc ou un jardin et cherchez un trèfle à quatre feuilles. Prenez le temps de vous concentrer sur votre recherche et de profiter de la nature qui vous entoure.",
      duration: Duration(minutes: 30),
      tags: ['price_all', 'season_spring', 'season_summer', 'family_all'],
    ),
    Capsule(
      id: 22,
      title: "Emprunter un livre à la bibliothèque",
      description: "Rendez-vous à la bibliothèque locale et empruntez un livre qui vous intéresse. Prenez le temps de lire et de vous immerger dans l'histoire ou les informations que le livre contient.",
      duration: Duration(minutes: 60),
      tags: ['price_little', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 23,
      title: "Imprimer un petit album photo",
      description: "Sélectionnez vos photos préférées sur votre téléphone ou votre ordinateur et imprimez-les pour créer un petit album photo. Organisez les photos de manière créative et ajoutez des légendes ou des décorations pour personnaliser votre album.",
      duration: Duration(minutes: 60),
      tags: ['price_little', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 24,
      title: "Faire du tri dans ses vêtements",
      description: "Prenez le temps de faire du tri dans votre garde-robe. Essayez les vêtements que vous n'avez pas portés depuis un moment et décidez lesquels vous souhaitez garder, donner ou jeter.",
      duration: Duration(minutes: 60),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 25,
      title: "Commencer un herbier",
      description: "Sortez dans la nature et cueillez différentes, plantes, fleurs ou feuilles que vous trouvez intéressantes. Séchez-les et collez-les dans un cahier pour créer votre propre herbier.",
      duration: Duration(minutes: 60),
      tags: ['price_all', 'season_spring', 'season_summer', 'family_all'],
    ),
    Capsule(
      id: 26,
      title: "Faire un petit montage photo",
      description: "Utilisez une application de montage photo pour créer un collage ou une composition à partir de vos photos préférées. Expérimentez avec différents filtres, effets et mises en page pour donner vie à vos souvenirs d'une manière créative et amusante.",
      duration: Duration(minutes: 60),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 27,
      title: "Aller au marché",
      description: "Visitez un marché local, que ce soit un marché de producteurs, un marché aux puces ou un marché artisanal. Prenez le temps de flâner entre les stands, de découvrir les produits locaux et de discuter avec les vendeurs.",
      duration: Duration(minutes: 60),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 28,
      title: "Regarder les étoiles",
      description: "Par une nuit claire, sortez à l'extérieur et regardez les étoiles. Prenez le temps d'admirer la beauté du ciel nocturne et de vous émerveiller devant l'immensité de l'univers.",
      duration: Duration(minutes: 10),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 29,
      title: "Regarder ses vieilles photos",
      description: "Prenez un moment pour regarder vos vieilles photos, que ce soit des photos physiques ou numériques. Revivez les souvenirs associés à ces photos et laissez-vous emporter par la nostalgie.",
      duration: Duration(minutes: 10),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 30,
      title: "Fabriquer une boite à souvenirs",
      description: "Prenez une boîte ou un récipient que vous aimez et transformez-le en une boîte à souvenirs. Décorez la boîte à votre goût et remplissez-la d'objets, de photos, de lettres ou de petits souvenirs qui ont une signification particulière pour vous.",
      duration: Duration(minutes: 60),
      tags: ['price_little', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 31,
      title: "Aller au zoo",
      description: "Visitez un zoo local pour découvrir la diversité de la faune et de la flore. Prenez le temps d'observer les animaux, d'apprendre sur leurs habitats et leurs comportements.",
      duration: Duration(minutes: 120),
      tags: ['price_high', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 32,
      title: "Aller visiter un musée",
      description: "Visitez un musée local pour découvrir l'art, l'histoire ou la culture. Prenez le temps d'explorer les différentes expositions, d'admirer les œuvres d'art.",
      duration: Duration(minutes: 120),
      tags: ['price_high', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 33,
      title: "Aller visiter un aquarium",
      description: "Visitez un aquarium local pour découvrir la vie marine et les écosystèmes aquatiques. Prenez le temps d'observer les différentes espèces de poissons, de coraux et d'autres créatures marines.",
      duration: Duration(minutes: 120),
      tags: ['price_high', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 34,
      title: "Essayer une nouvelle activité physique",
      description: "Essayez une nouvelle activité physique, que ce soit un sport, une danse, du yoga ou toute autre forme d'exercice que vous n'avez jamais pratiquée auparavant.",
      duration: Duration(minutes: 60),
      tags: ['price_little', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 35,
      title: "Commencer son propre livre de recettes",
      description: "Rassemblez vos recettes préférées, que ce soit des recettes familiales, des plats que vous avez découverts ou des créations culinaires que vous avez inventées.",
      duration: Duration(minutes: 15),
      tags: ['price_all', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 36,
      title: "Cuisiner un plat étranger",
      description: "Choisissez une cuisine étrangère que vous aimez ou que vous avez envie de découvrir, et essayez de cuisiner un plat typique de cette cuisine.",
      duration: Duration(minutes: 60),
      tags: ['price_little', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 37,
      title: "Aller au restaurants",
      description: "Offrez-vous une sortie au restaurant pour déguster un bon repas dans une ambiance agréable. Choisissez un restaurant que vous aimez ou que vous avez envie de découvrir.",
      duration: Duration(minutes: 60),
      tags: ['price_high', 'season_all', 'family_all'],
    ),
    Capsule(
      id: 38,
      title: "Organiser un gouter pour ses proches",
      description: "Organisez un goûter pour vos proches en préparant des pâtisseries, des boissons chaudes ou froides, et en créant une ambiance conviviale. Invitez vos amis ou votre famille à partager ce moment de douceur et de convivialité avec vous.",
      duration: Duration(minutes: 120),
      tags: ['price_little', 'season_all', 'family_yes', 'family_near'],
    ),
  ];

}